<?php

namespace Scool\Enrollment\Providers;

    use Illuminate\Support\ServiceProvider;

    /**
     * Class EnrollmentServiceProvider
     * @package Scool\Enrollment\Providers
     */
    class EnrollmentMobileServiceProvider extends ServiceProvider {

    public function register()
    {
     //   return parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        $this->loadMigrations();
        $this->publishFactories();
    }

    public function loadMigrations()
    {
        $this->loadMigrationsFrom(__DIR__.'/../../database/migrations');
    }

    public function publishFactories(){
        $this->publishes(
          [__DIR__.'/../../database/Enrollment.php' =>
          database_path().'/factories/Enrollment.php'],
            "scool_enrollment"
        );
    }

}